- name: Installing nginx with ansible 
  hosts: localhosts
  become: yes
  tasks:
  - name: Nginx Module
    yum:
      name: nginx
      state: installed
  - name: nginx service started
    service:
      name: nginx
      state: started