- name: Install Nginx Server
  hosts: all
  become: yes
  tasks: 
  - name: Install Nginx
    yum:
      name: nginx
      state: installed
    tags:
    - installation
  - name: Starting the services
    service:
      name: nginx
      state: started
    tags:
    - started
  - name: Restarting the nginx server
    service:
      name: nginx
      state: restarted
    tags:
    - restart
  - name: stopping the nginx servers
    service:
      name: nginx
      state: stopped
    tags:
    - stop
  - name: uninstalling the nginx service
    service:
      name: nginx
      state: absent
    tags:
    - uninstall